CREATE TABLE `LESSON` (
	`LSN_NO`	NUMBER(4)	NOT NULL,
	`USER_ID`	VARCHAR2(50)	NOT NULL,
	`LOC_NO`	VARCHAR2(30)	NOT NULL,
	`LSN_TITLE`	VARCHAR2(200)	NOT NULL,
	`LSN_LV`	VARCHAR2(20)	NOT NULL,
	`LSN_DAYS`	NUMBER(3)	NOT NULL,
	`LSN_INTRO`	VARCHAR2(4000)	NOT NULL,
	`LSN_PRICE`	NUMBER(8)	NOT NULL,
	`LSN_PER_TIME`	NUMBER(3)	NOT NULL,
	`LSN_CNT_SUM`	NUMBER(2)	NOT NULL,
	`LSN_STAR_SUM`	NUMBER(4)	NULL,
	`LSN_STAR_PPL_CNT`	NUMBER(4)	NULL,
	`LSN_STATUS`	NUMBER(1)	NOT NULL,
	`LSN_REQ_DT`	DATE	NOT NULL,
	`LSN_APV_DT`	DATE	NULL,
	`LSN_RJT_REASON`	VARCHAR2(300)	NULL
);

CREATE TABLE `LESSON_REVIEW` (
	`LSN_LINE_NO`	NUMBER(4)	NOT NULL,
	`REVIEW`	VARCHAR2(1500)	NOT NULL,
	`REVIEW_DT`	DATE	NOT NULL,
	`REVIEW_EDIT_DT`	DATE	NOT NULL,
	`MY_STAR_SCORE`	NUMBER(1)	NULL
);

CREATE TABLE `USER_INFO` (
	`USER_ID`	VARCHAR2(50)	NOT NULL,
	`USER_NAME`	VARCHAR2(20)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL,
	`USER_PWD`	VARCHAR2(20)	NOT NULL,
	`USER_PHONE`	VARCHAR2(14)	NOT NULL,
	`USER_JOIN_DT`	DATE	NOT NULL,
	`USER_TYPE`	NUMBER(1)	NOT NULL,
	`USER_QUIT_STATUS`	NUMBER(1)	NOT NULL
);

CREATE TABLE `PRO_INFO` (
	`USER_ID`	VARCHAR2(50)	NOT NULL,
	`PRO_CAREER`	VARCHAR2(4000)	NOT NULL
);

CREATE TABLE `LESSON_CLASSIFICATION` (
	`CLUB_NO`	NUMBER(1)	NOT NULL,
	`LSN_NO`	NUMBER(4)	NOT NULL
);

CREATE TABLE `LESSON_LINE` (
	`LSN_LINE_NO`	NUMBER(4)	NOT NULL,
	`USER_ID`	VARCHAR2(50)	NOT NULL,
	`LSN_NO`	NUMBER(4)	NOT NULL,
	`PAYMENT_NO`	NUMBER(4)	NOT NULL,
	`LSN_EXP_DT`	DATE	NULL,
	`STDT_LSN_STATUS`	NUMBER(1)	NOT NULL
);

CREATE TABLE `LESSON_HISTORY` (
	`LSN_CHK_DT`	DATE	NOT NULL,
	`LSN_LINE_NO`	NUMBER(4)	NOT NULL
);

CREATE TABLE `MEET_BOARD` (
	`MEET_BOARD_NO`	NUMBER(5)	NOT NULL,
	`MEET_CTG_NO`	NUMBER(1)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL,
	`MEET_BOARD_TITLE`	VARCHAR(200)	NOT NULL,
	`MEET_BOARD_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`MEET_BOARD_DT`	DATE	NOT NULL,
	`MEET_BOARD_VIEW_CNT`	NUMBER(4)	NOT NULL,
	`MEET_BOARD_STATUS`	NUMBER(1)	NOT NULL,
	`MEET_BOARD_MEET_DT`	DATE	NOT NULL,
	`MEET_BOARD_CUR_CNT`	NUMBER(2)	NOT NULL,
	`MEET_BOARD_MAX_CNT`	NUMBER(2)	NOT NULL,
	`MEET_BOARD_LOCATION`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `QNA_BOARD` (
	`QNA_BOARD_NO`	NUMBER(5)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL,
	`QNA_BOARD_TITLE`	VARCHAR(200)	NOT NULL,
	`QNA_BOARD_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`QNA_BOARD_DT`	DATE	NOT NULL,
	`QNA_BOARD_SECRET`	NUMBER(1)	NOT NULL
);

CREATE TABLE `MEET_CATEGORY` (
	`MEET_CTG_NO`	NUMBER(1)	NOT NULL,
	`MEET_CTG_TITLE`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `MEET_MEMBER` (
	`MEET_MB_NO`	NUMBER(4)	NOT NULL,
	`MEET_BOARD_NO`	NUMBER(5)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `PAYMENT` (
	`PAYMENT_NO`	NUMBER(4)	NOT NULL,
	`PAYMENT_METHOD`	VARCHAR2(30)	NOT NULL,
	`PAYMENT_DT`	DATE	NULL
);

CREATE TABLE `RESALE_BOARD` (
	`RESALE_BOARD_NO`	NUMBER(5)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL,
	`RESALE_BOARD_TITLE`	VARCHAR(200)	NOT NULL,
	`RESALE_BOARD_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`RESALE_BOARD_DT`	DATE	NOT NULL,
	`RESALE_BOARD_VIEW_CNT`	NUMBER(4)	NULL,
	`RESALE_BOARD_LIKE_CNT`	NUMBER(3)	NULL,
	`RESALE_BOARD_CMT_CNT`	NUMBER(3)	NULL
);

CREATE TABLE `RESALE_COMMENT` (
	`RESALE_CMT_NO`	NUMBER(5)	NOT NULL,
	`RESALE_BOARD_NO`	NUMBER(5)	NOT NULL,
	`RESALE_CMT_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`RESALE_CMT_DT`	DATE	NOT NULL,
	`RESALE_CMT_PARENT_NO`	NUMBER(4)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `RESALE_LIKE` (
	`RESALE_LIKE_NO`	NUMBER(4)	NOT NULL,
	`RESALE_BOARD_NO`	NUMBER(5)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `ROUND_REVIEW_BOARD` (
	`ROUND_REVIEW_BOARD_NO`	NUMBER(5)	NOT NULL,
	`ROUND_REVIEW_BOARD_TITLE`	VARCHAR(200)	NOT NULL,
	`ROUND_REVIEW_BOARD_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL,
	`ROUND_REVIEW_BOARD_DT`	DATE	NOT NULL,
	`ROUND_REVIEW_BOARD_VIEW_CNT`	NUMBER(4)	NULL,
	`ROUND_REVIEW_BOARD_LIKE_CNT`	NUMBER(3)	NULL,
	`ROUND_REVIEW_BOARD_CMT_CNT`	NUMBER(3)	NULL,
	`ROUND_REVIEW_BOARD_LATITUDE`	VARCHAR2(100)	NULL,
	`ROUND_REVIEW_BOARD_LONGITUDE`	VARCHAR2(100)	NULL
);

CREATE TABLE `NOTICE_BOARD` (
	`NOTICE_BOARD_NO`	NUMBER(5)	NOT NULL,
	`NOTICE_BOARD_TITLE`	VARCHAR(200)	NOT NULL,
	`NOTICE_BOARD_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`NOTICE_BOARD_DT`	DATE	NOT NULL,
	`NOTICE_BOARD_VIEW_CNT`	NUMBER(4)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL,
	`NOTICE_BOARD_LIKE_CNT`	NUMBER(3)	NULL,
	`NOTICE_BOARD_CMT_CNT`	NUMBER(3)	NULL
);

CREATE TABLE `ROUND_REVIEW_COMMENT` (
	`ROUND_REVIEW_CMT_NO`	NUMBER(5)	NOT NULL,
	`ROUND_REVIEW_BOARD_NO`	NUMBER(5)	NOT NULL,
	`ROUND_REVIEW_CMT_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`ROUND_REVIEW_CMT_DT`	DATE	NOT NULL,
	`ROUND_REVIEW_CMT_PARENT_NO`	NUMBER(4)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `NOTICE_LIKE` (
	`NOTICE_LIKE_NO`	NUMBER(4)	NOT NULL,
	`NOTICE_BOARD_NO`	NUMBER(5)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NULL
);

CREATE TABLE `ROUND_REVIEW_LIKE` (
	`ROUND_REVIEW_LIKE_NO`	NUMBER(4)	NOT NULL,
	`ROUND_REVIEW_BOARD_NO`	NUMBER(5)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `NOTICE_COMMENT` (
	`NOTICE_CMT_NO`	NUMBER(5)	NOT NULL,
	`NOTICE_BOARD_NO`	NUMBER(5)	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL,
	`NOTICE_CMT_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`NOTICE_CMT_DT`	DATE	NOT NULL,
	`NOTICE_CMT_PARENT_NO`	NUMBER(4)	NOT NULL
);

CREATE TABLE `QNA_COMMENT` (
	`QNA_BOARD_NO`	NUMBER(5)	NOT NULL,
	`QNA_CMT_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`QNA_CMT_DT`	DATE	NOT NULL,
	`USER_NICKNAME`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `SIGNUP_APPROVAL` (
	`APPROVAL_USER_ID`	VARCHAR2(50)	NOT NULL,
	`APPROVAL_USER_NAME`	VARCHAR2(20)	NOT NULL,
	`APPROVAL_USER_NICKNAME`	VARCHAR2(30)	NOT NULL,
	`APPROVAL_USER_PWD`	VARCHAR2(20)	NOT NULL,
	`APPROVAL_USER_PHONE`	VARCHAR2(14)	NOT NULL
);

ALTER TABLE `LESSON` ADD CONSTRAINT `PK_LESSON` PRIMARY KEY (
	`LSN_NO`
);

ALTER TABLE `LESSON_REVIEW` ADD CONSTRAINT `PK_LESSON_REVIEW` PRIMARY KEY (
	`LSN_LINE_NO`
);

ALTER TABLE `USER_INFO` ADD CONSTRAINT `PK_USER_INFO` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `PRO_INFO` ADD CONSTRAINT `PK_PRO_INFO` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `LESSON_CLASSIFICATION` ADD CONSTRAINT `PK_LESSON_CLASSIFICATION` PRIMARY KEY (
	`CLUB_NO`,
	`LSN_NO`
);

ALTER TABLE `LESSON_LINE` ADD CONSTRAINT `PK_LESSON_LINE` PRIMARY KEY (
	`LSN_LINE_NO`
);

ALTER TABLE `LESSON_HISTORY` ADD CONSTRAINT `PK_LESSON_HISTORY` PRIMARY KEY (
	`LSN_CHK_DT`,
	`LSN_LINE_NO`
);

ALTER TABLE `MEET_BOARD` ADD CONSTRAINT `PK_MEET_BOARD` PRIMARY KEY (
	`MEET_BOARD_NO`
);

ALTER TABLE `QNA_BOARD` ADD CONSTRAINT `PK_QNA_BOARD` PRIMARY KEY (
	`QNA_BOARD_NO`
);

ALTER TABLE `MEET_CATEGORY` ADD CONSTRAINT `PK_MEET_CATEGORY` PRIMARY KEY (
	`MEET_CTG_NO`
);

ALTER TABLE `MEET_MEMBER` ADD CONSTRAINT `PK_MEET_MEMBER` PRIMARY KEY (
	`MEET_MB_NO`
);

ALTER TABLE `PAYMENT` ADD CONSTRAINT `PK_PAYMENT` PRIMARY KEY (
	`PAYMENT_NO`
);

ALTER TABLE `RESALE_BOARD` ADD CONSTRAINT `PK_RESALE_BOARD` PRIMARY KEY (
	`RESALE_BOARD_NO`
);

ALTER TABLE `RESALE_COMMENT` ADD CONSTRAINT `PK_RESALE_COMMENT` PRIMARY KEY (
	`RESALE_CMT_NO`
);

ALTER TABLE `RESALE_LIKE` ADD CONSTRAINT `PK_RESALE_LIKE` PRIMARY KEY (
	`RESALE_LIKE_NO`
);

ALTER TABLE `ROUND_REVIEW_BOARD` ADD CONSTRAINT `PK_ROUND_REVIEW_BOARD` PRIMARY KEY (
	`ROUND_REVIEW_BOARD_NO`
);

ALTER TABLE `NOTICE_BOARD` ADD CONSTRAINT `PK_NOTICE_BOARD` PRIMARY KEY (
	`NOTICE_BOARD_NO`
);

ALTER TABLE `ROUND_REVIEW_COMMENT` ADD CONSTRAINT `PK_ROUND_REVIEW_COMMENT` PRIMARY KEY (
	`ROUND_REVIEW_CMT_NO`
);

ALTER TABLE `NOTICE_LIKE` ADD CONSTRAINT `PK_NOTICE_LIKE` PRIMARY KEY (
	`NOTICE_LIKE_NO`
);

ALTER TABLE `ROUND_REVIEW_LIKE` ADD CONSTRAINT `PK_ROUND_REVIEW_LIKE` PRIMARY KEY (
	`ROUND_REVIEW_LIKE_NO`
);

ALTER TABLE `NOTICE_COMMENT` ADD CONSTRAINT `PK_NOTICE_COMMENT` PRIMARY KEY (
	`NOTICE_CMT_NO`
);

ALTER TABLE `QNA_COMMENT` ADD CONSTRAINT `PK_QNA_COMMENT` PRIMARY KEY (
	`QNA_BOARD_NO`
);

ALTER TABLE `SIGNUP_APPROVAL` ADD CONSTRAINT `PK_SIGNUP_APPROVAL` PRIMARY KEY (
	`APPROVAL_USER_ID`
);

ALTER TABLE `LESSON_REVIEW` ADD CONSTRAINT `FK_LESSON_LINE_TO_LESSON_REVIEW_1` FOREIGN KEY (
	`LSN_LINE_NO`
)
REFERENCES `LESSON_LINE` (
	`LSN_LINE_NO`
);

ALTER TABLE `PRO_INFO` ADD CONSTRAINT `FK_USER_INFO_TO_PRO_INFO_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER_INFO` (
	`USER_ID`
);

ALTER TABLE `LESSON_CLASSIFICATION` ADD CONSTRAINT `FK_LESSON_TO_LESSON_CLASSIFICATION_1` FOREIGN KEY (
	`LSN_NO`
)
REFERENCES `LESSON` (
	`LSN_NO`
);

ALTER TABLE `LESSON_HISTORY` ADD CONSTRAINT `FK_LESSON_LINE_TO_LESSON_HISTORY_1` FOREIGN KEY (
	`LSN_LINE_NO`
)
REFERENCES `LESSON_LINE` (
	`LSN_LINE_NO`
);

ALTER TABLE `QNA_COMMENT` ADD CONSTRAINT `FK_QNA_BOARD_TO_QNA_COMMENT_1` FOREIGN KEY (
	`QNA_BOARD_NO`
)
REFERENCES `QNA_BOARD` (
	`QNA_BOARD_NO`
);

